# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            elliott
tagline:          'precariat'
description:      'precariat, designer, generalist'
url:              http://elliott.io
baseurl:          /

author:
  name:           'Elliott Williams'
  url:            https://twitter.com/elliottwilliams

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
